// Renders the parity result as docs/migration/parity-report.md. Deterministic: no
// clock, sorted output, fixed number formatting.

import { LEGACY_REPOSITORY, LEGACY_REVISION } from "../../migrate/lib/legacy-source.mjs";

const n = (x) => Number(x).toLocaleString("en-US");
const cell = (s) => String(s).replace(/\|/g, "\\|").replace(/\n/g, " ");
const table = (head, rows) => [`| ${head.join(" | ")} |`, `| ${head.map(() => "---").join(" | ")} |`, ...rows.map((r) => `| ${r.map(cell).join(" | ")} |`)].join("\n");
const cmp = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

const ARTIFACT_NAMES = { taxonomy: "taxonomy.json", dossiers: "dossier frontmatter", scenarios: "scenarios.json", categories: "categories.json", semantics: "fixture-semantics.json", index: "fixture-index.json", corpus: "corpora (67 files)" };
const ARTIFACT_ORDER = ["taxonomy", "dossiers", "scenarios", "categories", "semantics", "index", "corpus"];

export function renderParityReport(r) {
  const totals = { legacyLeaves: 0, equal: 0, explained: 0, unexplained: 0 };
  for (const a of r.perArtifact.values()) for (const k of Object.keys(totals)) totals[k] += a[k];
  const explainedByClass = new Map();
  for (const s of r.rules) explainedByClass.set(s.rule.class, (explainedByClass.get(s.rule.class) ?? 0) + s.count);
  const ruleRows = [...r.rules].sort((a, b) => cmp(a.rule.class, b.rule.class) || b.count - a.count || cmp(a.rule.id, b.rule.id));
  const verdict = r.unexplained.length === 0 && r.unusedRules.length === 0 && r.consumer.indexProblems.length === 0 && r.consumer.corpusFailures.length === 0 && r.conformance.every((c) => c.valid);

  const out = [];
  out.push("# Legacy parity report");
  out.push("");
  out.push(`<!-- Generated by scripts/parity/run.mjs ${r.parityVersion}. Do not edit; run \`npm run parity\`. -->`);
  out.push("");
  out.push(`Legacy: \`${LEGACY_REPOSITORY}\` at \`${LEGACY_REVISION}\`, read-only via \`git archive\`. The legacy fixture generators are run over that extraction and every generated corpus is checked against the legacy \`generated-corpora.json\` hash manifest before it is compared. Canonical: this repository's \`records/\`, projected by \`scripts/export/legacy-projection.mjs\` (generator ${r.generator.version}).`);
  out.push("");
  out.push("The legacy repository stays authoritative. This report proves how far the generated projection reproduces its benchmark inputs; it proposes deleting nothing. The cutover rule and what remains are in `docs/migration/cutover.md`; the decision is `docs/decisions/0006-legacy-projection-and-parity.md`.");
  out.push("");
  out.push("## Result");
  out.push("");
  out.push(`**Unexplained differences: ${n(r.unexplained.length)}.** ${verdict ? "The run passes." : "The run FAILS (see below)."}`);
  out.push("");
  out.push(table(["Measure", "Value"], [
    ["projection source revision (records tree sha256)", `\`${r.sourceRevision.digest}\``],
    ["schema revision", r.schemaRevision],
    ["projection digest (over every artifact digest)", `\`${r.projectionDigest}\``],
    ["artifacts projected", n(r.artifactCount)],
    ["legacy documents compared", n(r.docRows.length)],
    ["legacy leaf values compared", n(totals.legacyLeaves)],
    ["identical after normalization", n(totals.equal)],
    ["explained differences (leaf values)", n(totals.explained)],
    ["unexplained differences (leaf values)", n(totals.unexplained)],
    ["arrays that differed only in order (ignored, see Normalization)", n(r.orderOnlyTotal)],
    ["explained-difference rules", `${n(r.rules.length)} (all matched; unused: ${n(r.unusedRules.length)})`],
  ]));
  out.push("");
  out.push("A leaf value is one scalar (or one empty container) at a normalized path. A field present on one side only counts as one difference per leaf.");
  out.push("");
  out.push("## Per artifact");
  out.push("");
  out.push(table(["Artifact", "Documents", "Legacy leaves", "Identical", "Explained", "Unexplained", "Order-only arrays"], ARTIFACT_ORDER.filter((a) => r.perArtifact.has(a)).map((a) => {
    const x = r.perArtifact.get(a);
    return [ARTIFACT_NAMES[a], n(x.docs), n(x.legacyLeaves), n(x.equal), n(x.explained), n(x.unexplained), n(x.orderOnly)];
  })));
  out.push("");
  out.push("## Normalization (what is ignored, and nothing else)");
  out.push("");
  out.push("- Whitespace and key order: both sides are parsed as JSON (dossier frontmatter as YAML) before comparison.");
  out.push("- Array element order. Arrays of objects are matched by identity (`id`, else `slug`, else a span's `start:end`); arrays of scalars (family ids, detectors, citations) are compared as sets, so a citation listed twice is one member. The legacy files are in authoring order and the projection is sorted by stable id, which is what the order-only count above measures. Legacy consumers that depend on array order (category order in `benchmarks/categories.json` drives run order) must sort or overlay it.");
  out.push("- Nothing else. Case, punctuation, URL forms and text are compared exactly.");
  out.push("");
  out.push("## Explained differences");
  out.push("");
  out.push(`Every explained difference matched a rule in \`scripts/parity/rules.json\`. A rule names the artifact, a path pattern, the change, optional value constraints, and optionally a predicate (\`scripts/parity/lib/predicates.mjs\`) that checks the stated cause against the records and the legacy document. A rule that matches nothing fails the run.`);
  out.push("");
  out.push(table(["Class", "Leaf values"], [...explainedByClass].sort((a, b) => b[1] - a[1] || cmp(a[0], b[0])).map(([c, k]) => [c, n(k)])));
  out.push("");
  out.push(table(["Rule", "Class", "Artifact", "Change", "Leaf values", "Entities", "Example"], ruleRows.map((s) => [`\`${s.rule.id}\``, s.rule.class, s.rule.artifact, s.rule.change, n(s.count), n(s.entities.size), `\`${s.examples[0] ?? ""}\``.slice(0, 130)])));
  out.push("");
  out.push("### Justifications");
  out.push("");
  for (const s of ruleRows) {
    out.push(`- \`${s.rule.id}\` (${s.rule.class}; ${n(s.count)} leaf values in ${n(s.entities.size)} entities${s.rule.predicate ? `; checked by \`${s.rule.predicate}\`` : ""}): ${s.rule.justification}`);
  }
  out.push("");
  out.push("## Unexplained differences");
  out.push("");
  if (!r.unexplained.length) out.push("None.");
  else {
    const byPattern = new Map();
    for (const d of r.unexplained) {
      const k = `${d.artifact} | ${d.pattern} | ${d.change}`;
      const e = byPattern.get(k) ?? { count: 0, examples: [] };
      e.count += 1;
      if (e.examples.length < 2) e.examples.push(`${d.docId}: ${d.path} legacy=${JSON.stringify(d.legacy)?.slice(0, 60)} projected=${JSON.stringify(d.projected)?.slice(0, 60)}`);
      byPattern.set(k, e);
    }
    out.push(table(["Artifact, pattern, change", "Count", "Examples"], [...byPattern].sort((a, b) => b[1].count - a[1].count || cmp(a[0], b[0])).slice(0, 60).map(([k, e]) => [k.replace(/ \\| /g, ", "), n(e.count), e.examples.join("; ")])));
  }
  if (r.unusedRules.length) out.push("", `Unused rules (fail the run): ${r.unusedRules.map((x) => `\`${x}\``).join(", ")}.`);
  out.push("");
  out.push("## Legacy code run over the projection");
  out.push("");
  out.push(table(["Check", "Result"], [
    ["legacy `fixtureIndexProblems` (benchmarks/lib/fixture-index.ts) over the projected index", r.consumer.indexProblems.length ? r.consumer.indexProblems.join("; ") : "no problems"],
    [`legacy \`validateCorpus\` (benchmarks/lib/scoring.ts) over the ${n(r.consumer.corpora)} projected corpora`, r.consumer.corpusFailures.length ? r.consumer.corpusFailures.map(([p, m]) => `${p}: ${m}`).join("; ") : "all accepted"],
    ...r.conformance.map((c) => [`legacy schema \`${c.schema}\` over \`${c.artifactPath}\``, c.valid ? "valid" : `INVALID: ${c.errors.join("; ")}`]),
  ]));
  out.push("");
  out.push("## Legacy files and what the projection does about each");
  out.push("");
  out.push("The files benchmark consumers read, at the pinned revision. Consumers are the legacy source files (benchmarks, scripts, tests, src, scanners) that name the file at a name boundary; the count is an upper bound on what a switch to the projection has to touch (a file may name it only in a comment).");
  out.push("");
  out.push(table(["Legacy file", "Disposition", "Entries", "Bytes", "Consumers", "Why"], r.inventory.map((f) => [`\`${f.path}\``, f.disposition + (f.overlay ? ` (overlay \`${f.overlay}\`)` : ""), f.entries === null ? "n/a" : typeof f.entries === "string" ? f.entries : n(f.entries), f.bytes === null || typeof f.bytes === "string" ? (f.bytes ?? "n/a") : n(f.bytes), n(f.consumers.length), f.justification])));
  out.push("");
  out.push("Dispositions: `projected` (compared above), `overlay` (the consumer supplies it; interface in `overlay-interface.json`), `replaced` (superseded by the projection manifest), `product-owned` (Redact Secret qualification or measurement state, never exported here), `not-projected` (follow-up), `not-imported` (out of scope).");
  out.push("");
  const missing = r.inventory.filter((f) => !f.exists);
  if (missing.length) out.push(`Inventory entries whose file does not exist at the pinned revision (fail the run): ${missing.map((f) => `\`${f.path}\``).join(", ")}.`, "");
  out.push(`Dossier prose: the ${n(r.dossiers.proseBytes)} bytes of narrative below the frontmatter of the legacy dossiers are hand-written legacy prose and are not projected (ADR 0004 keeps only verbatim review events). Excluded non-dossier files: ${r.dossiers.excluded.map((x) => `\`${x}\``).join(", ")}.`);
  out.push("");
  out.push("### Consumers per projected or overlay file");
  out.push("");
  for (const f of r.inventory.filter((x) => ["projected", "overlay"].includes(x.disposition))) {
    const shown = f.consumers.slice(0, 8).map((c) => `\`${c}\``).join(", ");
    out.push(`- \`${f.path}\`: ${n(f.consumers.length)} file(s)${f.consumers.length ? `: ${shown}${f.consumers.length > 8 ? `, and ${f.consumers.length - 8} more` : ""}` : ""}`);
  }
  out.push("");
  out.push("## Not compared");
  out.push("");
  out.push(r.projectedOnly.length ? `- \`${r.projectedOnly.join("`, `")}\`: projected documents with no legacy counterpart.` : "- Every projected JSON document has a legacy counterpart that was compared, except the two metadata files below.");
  out.push("- `credential-eval/corpus-snapshot.json` is credential-eval's input contract, not a legacy file. Its truth fields are the ones compared above; it is validated in `tests/export-legacy.test.mjs` and by credential-eval's own validator (docs/decisions/0006).");
  out.push("- `overlay-interface.json` and `provenance-manifest.json` are projection metadata with no legacy counterpart.");
  out.push("- Holdout and qualification data: never exported from this repository.");
  out.push("");
  return `${out.join("\n")}\n`;
}

export function verdictOf(r) {
  const missing = r.inventory.filter((f) => !f.exists).length;
  return r.unexplained.length === 0 && r.unusedRules.length === 0 && r.consumer.indexProblems.length === 0 && r.consumer.corpusFailures.length === 0 && r.conformance.every((c) => c.valid) && missing === 0;
}
