// The import baseline (ADR 0015): what the migration importers produced at the pinned legacy
// revision, as a manifest of paths and sha256 digests, and how the working tree relates to it.
//
//   docs/migration/baseline-manifest.json     generated; path + sha256 + producing importer of every
//                                             baseline file (records, legacy map, importer reports)
//   docs/migration/baseline-amendments.json   authored; one entry (path, change, reason) for every
//                                             baseline record that a reviewed change edited or removed
//
// The tree is classified against the manifest, never silently:
//
//   unchanged   byte-identical to the baseline
//   edited      a baseline record whose bytes differ: needs a declared amendment, or it fails
//   removed     a baseline record that is gone: needs a declared amendment, or it fails
//   added       a file the baseline does not list (a new provider, family, case...): always allowed,
//               counted, never an amendment
//
// Records under records/ may be amended. Everything else in the manifest (the legacy map, the
// importer reports) is an immutable reference: any difference fails, because only a re-pin, which
// regenerates the manifest, may change it. The historical checks (migrate:*:check, export:legacy:check,
// parity:check) regenerate the baseline from the pinned legacy revision and compare it with this
// manifest, so "the baseline is reproducible at the pin" is proven independently of the tree.
//
// This module reads files and nothing else: no legacy checkout, no network. Importers live in
// scripts/migrate; the code that regenerates the baseline is scripts/migrate/lib/baseline-build.mjs.

import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { listJson, repoRoot } from "./validator.mjs";

export const MANIFEST_PATH = "docs/migration/baseline-manifest.json";
export const AMENDMENTS_PATH = "docs/migration/baseline-amendments.json";
export const MANIFEST_FORMAT = "credential-evidence/import-baseline-manifest";
export const AMENDMENTS_FORMAT = "credential-evidence/baseline-amendments";
export const GENERATOR = { name: "credential-evidence/import-baseline", version: "1.0.0" };
export const OWNERS = ["migrate:taxonomy", "migrate:cases", "migrate:narratives"];
export const CHANGES = ["edited", "removed"];
const MIN_REASON = 12;

const cmp = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
export const sha256 = (data) => createHash("sha256").update(data).digest("hex");
const HEX64 = /^[0-9a-f]{64}$/;

/** Directory-walk order of the tree readers (sorted names, depth first), for repo-relative `/` paths. */
export const walkOrder = (a, b) => {
  const x = a.split("/");
  const y = b.split("/");
  for (let i = 0; i < Math.min(x.length, y.length); i++) if (x[i] !== y[i]) return x[i] < y[i] ? -1 : 1;
  return x.length - y.length;
};

/** Records may be amended; the legacy map and the importer reports are immutable references. */
export const isAmendable = (path) => path.startsWith("records/");

/** Digest over the sorted `<path> <sha256>` lines: one value that names the whole baseline. */
export const baselineDigest = (files) => sha256(files.map((f) => `${f.path} ${f.sha256}`).sort(cmp).join("\n"));

// ---------------------------------------------------------------- manifest

/** One entry per line keeps the file diff-friendly; the content is plain JSON. */
export function serializeManifest({ legacy, files }) {
  const sorted = [...files].sort((a, b) => cmp(a.path, b.path));
  const head = {
    format: MANIFEST_FORMAT,
    formatVersion: 1,
    note: "Generated by the migration importers (npm run migrate:taxonomy, migrate:cases, migrate:narratives). The baseline is what the pinned legacy revision produced; records may be amended afterwards only through docs/migration/baseline-amendments.json (ADR 0015). Do not edit by hand.",
    legacy,
    generator: GENERATOR,
    baselineDigest: baselineDigest(sorted),
    fileCount: sorted.length,
  };
  const lines = Object.entries(head).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
  return `{\n${lines.join("\n")}\n  "files": [\n${sorted.map((f) => `    ${JSON.stringify({ path: f.path, sha256: f.sha256, owner: f.owner })}`).join(",\n")}\n  ]\n}\n`;
}

/** Parsed manifest, or null when the file does not exist. Throws on a malformed one. */
export function loadManifest(root = repoRoot) {
  const file = join(root, MANIFEST_PATH);
  if (!existsSync(file)) return null;
  const m = JSON.parse(readFileSync(file, "utf8"));
  const problems = manifestProblems(m);
  if (problems.length) throw new Error(`${MANIFEST_PATH} is malformed:\n${problems.join("\n")}`);
  return m;
}

export function manifestProblems(m) {
  const problems = [];
  if (m?.format !== MANIFEST_FORMAT || m.formatVersion !== 1) return [`format must be ${MANIFEST_FORMAT} version 1`];
  if (!Array.isArray(m.files) || !m.files.length) return ["files must be a non-empty array"];
  let prev = "";
  for (const f of m.files) {
    if (typeof f.path !== "string" || !HEX64.test(f.sha256 ?? "") || !OWNERS.includes(f.owner)) problems.push(`bad entry ${JSON.stringify(f)}`);
    else if (f.path <= prev) problems.push(`entries must be sorted and unique at ${f.path}`);
    prev = f.path ?? prev;
  }
  if (m.fileCount !== m.files.length) problems.push(`fileCount ${m.fileCount} is not ${m.files.length}`);
  if (!problems.length && m.baselineDigest !== baselineDigest(m.files)) problems.push("baselineDigest does not match the entries");
  return problems;
}

/** Replace one importer's slice of the manifest (called by an importer's write mode) and write it. */
export function updateManifestOwner({ root = repoRoot, owner, generated, legacy }) {
  const current = loadManifest(root);
  const kept = (current?.files ?? []).filter((f) => f.owner !== owner);
  const fresh = [...generated].map(([path, text]) => ({ path, sha256: sha256(text), owner }));
  const text = serializeManifest({ legacy: legacy ?? current?.legacy, files: [...kept, ...fresh] });
  mkdirSync(dirname(join(root, MANIFEST_PATH)), { recursive: true });
  writeFileSync(join(root, MANIFEST_PATH), text);
}

/**
 * Compare a regenerated slice with the manifest: what an importer's `--check` proves. The generated
 * set must be exactly the manifest's entries for `owner`, byte for byte (by digest).
 */
export function compareWithManifest(generated, manifest, owner) {
  const problems = [];
  const entries = new Map(manifest.files.filter((f) => f.owner === owner).map((f) => [f.path, f.sha256]));
  for (const [path, text] of generated) {
    if (!entries.has(path)) problems.push(`not in the baseline manifest: ${path}`);
    else if (entries.get(path) !== sha256(text)) problems.push(`differs from the baseline manifest: ${path}`);
  }
  for (const path of entries.keys()) if (!generated.has(path)) problems.push(`in the baseline manifest but not regenerated: ${path}`);
  return problems;
}

// -------------------------------------------------------------- amendments

export function loadAmendments(root = repoRoot) {
  const file = join(root, AMENDMENTS_PATH);
  if (!existsSync(file)) return { amendments: [], problems: [`missing: ${AMENDMENTS_PATH}`] };
  const doc = JSON.parse(readFileSync(file, "utf8"));
  const problems = [];
  if (doc.format !== AMENDMENTS_FORMAT || doc.formatVersion !== 1) problems.push(`${AMENDMENTS_PATH}: format must be ${AMENDMENTS_FORMAT} version 1`);
  if (!Array.isArray(doc.amendments)) return { amendments: [], problems: [...problems, `${AMENDMENTS_PATH}: amendments must be an array`] };
  let prev = "";
  for (const a of doc.amendments) {
    const where = `${AMENDMENTS_PATH}: ${a?.path}`;
    if (typeof a?.path !== "string" || !CHANGES.includes(a.change)) problems.push(`${where}: needs path and change (${CHANGES.join(" or ")})`);
    else if (typeof a.reason !== "string" || a.reason.trim().length < MIN_REASON) problems.push(`${where}: a reason of at least ${MIN_REASON} characters is required (the stated cause of the change)`);
    else if (a.ref !== undefined && typeof a.ref !== "string") problems.push(`${where}: ref must be a string`);
    else if (!isAmendable(a.path)) problems.push(`${where}: only records under records/ can be amended; the legacy map and the importer reports are immutable references (ADR 0015)`);
    if (typeof a?.path === "string") {
      if (a.path <= prev) problems.push(`${where}: entries must be sorted by path and unique`);
      prev = a.path;
    }
  }
  return { amendments: doc.amendments, problems };
}

export function serializeAmendments(amendments) {
  const sorted = [...amendments].sort((a, b) => cmp(a.path, b.path));
  const head = {
    format: AMENDMENTS_FORMAT,
    formatVersion: 1,
    note: "One entry per baseline record that a reviewed change edited or removed after the import (ADR 0015). Adding a record needs no entry. Declare with `npm run baseline:amend`; `npm run baseline:check` fails on an undeclared edit or removal and on an entry the tree no longer needs.",
  };
  const lines = Object.entries(head).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
  return `{\n${lines.join("\n")}\n  "amendments": [\n${sorted.map((a) => `    ${JSON.stringify(a)}`).join(",\n")}${sorted.length ? "\n" : ""}  ]\n}\n`;
}

// ------------------------------------------------------------ tree against baseline

/** Sha256 of every JSON file the baseline can cover on disk: records/** and migration/**, keyed by repo-relative path. */
export function treeDigests(root = repoRoot) {
  const out = new Map();
  for (const dir of ["records", "migration"]) {
    const abs = join(root, dir);
    if (!existsSync(abs)) continue;
    for (const f of listJson(abs)) out.set(relative(root, f).split("\\").join("/"), sha256(readFileSync(f)));
  }
  return out;
}

const digestOfFile = (root, path) => {
  const abs = join(root, path);
  return existsSync(abs) ? sha256(readFileSync(abs)) : null;
};

/**
 * Classify the working tree against the manifest and the amendments. `problems` is empty exactly when
 * every difference from the baseline is declared and every declaration is still needed.
 */
export function classifyTree(root = repoRoot) {
  const manifest = loadManifest(root);
  const result = { manifest, unchanged: [], edited: [], removed: [], added: [], problems: [] };
  if (!manifest) {
    result.problems.push(`missing: ${MANIFEST_PATH}; run the importers (npm run migrate:taxonomy, migrate:cases, migrate:narratives)`);
    return result;
  }
  const { amendments, problems } = loadAmendments(root);
  result.problems.push(...problems);
  const declared = new Map(amendments.map((a) => [a.path, a]));
  const tree = treeDigests(root);
  const baseline = new Map(manifest.files.map((f) => [f.path, f]));

  for (const f of manifest.files) {
    const have = f.path.startsWith("docs/") ? digestOfFile(root, f.path) : (tree.get(f.path) ?? null);
    const a = declared.get(f.path);
    if (have === f.sha256) {
      result.unchanged.push(f.path);
      if (a) result.problems.push(`stale amendment: ${f.path} equals the baseline again; remove its entry from ${AMENDMENTS_PATH}`);
      continue;
    }
    const change = have === null ? "removed" : "edited";
    (change === "removed" ? result.removed : result.edited).push(f.path);
    if (!isAmendable(f.path)) result.problems.push(`${change} immutable reference: ${f.path} (only a re-pin regenerates it; ADR 0015)`);
    else if (!a) result.problems.push(`undeclared ${change}: ${f.path}; declare it with npm run baseline:amend -- ${f.path} --reason "<why>"`);
    else if (a.change !== change) result.problems.push(`${f.path} is ${change} but ${AMENDMENTS_PATH} says ${a.change}`);
  }
  for (const a of amendments) if (!baseline.has(a.path)) result.problems.push(`amendment for a path the baseline does not list: ${a.path} (a new record needs no amendment)`);
  for (const path of tree.keys()) {
    if (baseline.has(path)) continue;
    result.added.push(path);
    if (path.startsWith("migration/")) result.problems.push(`added under migration/: ${path}; the legacy map is closed, new records get no legacy name`);
  }
  for (const k of ["unchanged", "edited", "removed", "added"]) result[k].sort(cmp);
  return result;
}

export function summarize(c) {
  const n = (x) => x.length.toLocaleString("en-US");
  return `baseline ${c.manifest.baselineDigest.slice(0, 12)} (legacy ${c.manifest.legacy.revision.slice(0, 8)}): ${n(c.manifest.files.map((f) => f.path))} files, ${n(c.unchanged)} unchanged, ${n(c.edited)} edited, ${n(c.removed)} removed (all declared); ${n(c.added)} post-import file(s) added`;
}

/** Declare an amendment for a baseline record the tree now differs from. Returns the entry. */
export function declareAmendment({ root = repoRoot, path, reason, ref }) {
  const manifest = loadManifest(root);
  if (!manifest) throw new Error(`missing: ${MANIFEST_PATH}`);
  const entry = manifest.files.find((f) => f.path === path);
  if (!entry) throw new Error(`${path} is not in the baseline: a new record needs no amendment`);
  if (!isAmendable(path)) throw new Error(`${path} is an immutable reference, not a record (ADR 0015)`);
  const have = digestOfFile(root, path);
  if (have === entry.sha256) throw new Error(`${path} equals the baseline: nothing to declare`);
  const change = have === null ? "removed" : "edited";
  if (typeof reason !== "string" || reason.trim().length < MIN_REASON) throw new Error(`--reason needs at least ${MIN_REASON} characters: the cause of the change`);
  const { amendments } = loadAmendments(root);
  const next = amendments.filter((a) => a.path !== path);
  const amendment = { path, change, reason: reason.trim(), ...(ref ? { ref } : {}) };
  next.push(amendment);
  writeFileSync(join(root, AMENDMENTS_PATH), serializeAmendments(next));
  return amendment;
}

/** Declare every undeclared difference with one reason (used by tools that know their cause). */
export function declareAll({ root = repoRoot, reason, ref }) {
  const c = classifyTree(root);
  const out = [];
  for (const path of [...c.edited, ...c.removed]) {
    if (!isAmendable(path)) continue;
    const { amendments } = loadAmendments(root);
    if (amendments.some((a) => a.path === path)) continue;
    out.push(declareAmendment({ root, path, reason, ref }));
  }
  return out;
}

// --------------------------------------------------------- ownership (read-only view)

const cache = new Map();
/** Baseline path to the importer that produced it (cached per root); empty when there is no manifest. */
export function baselineOwners(root = repoRoot) {
  if (!cache.has(root)) cache.set(root, new Map((loadManifest(root)?.files ?? []).map((f) => [f.path, f.owner])));
  return cache.get(root);
}
