// Deterministic Markdown migration report for the case and fixture import.
// Same input revision => byte-identical output. Counts come from the import
// itself; nothing here is hand-edited.

import { LEGACY_REPOSITORY } from "./legacy-source.mjs";
import { IMPORTER_VERSION } from "./case-import.mjs";

const cmp = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
const n = (x) => String(x).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
const row = (...cells) => `| ${cells.join(" | ")} |`;
const table = (head, rows) => [row(...head), row(...head.map(() => "---")), ...rows.map((r) => row(...r))].join("\n");

export function renderCasesReport({ model, files, digest }) {
  const R = model.counts;
  const c = (k) => R.get(k);
  const withPrefix = (prefix) =>
    [...R.counts.keys()]
      .filter((k) => k.startsWith(prefix))
      .sort(cmp)
      .map((k) => [k.slice(prefix.length), R.get(k)]);
  const bytesOf = (prefix) => [...files].filter(([p]) => p.startsWith(prefix)).reduce((s, [, t]) => s + Buffer.byteLength(t), 0);
  const kib = (b) => n(Math.round(b / 1024));
  const out = [];
  const push = (...lines) => out.push(...lines.flatMap((l) => [l, ""]));

  const cases = model.caseRecords;
  const famUsed = new Set(cases.flatMap((x) => x.families.map((f) => f.family)));
  const famAll = [...model.families.keys()].sort(cmp);
  const unused = famAll.filter((f) => !famUsed.has(f));
  const fixturesTotal = c("fixtures:generated") + c("fixtures:authored");

  push(
    "# Cases and fixtures import report",
    `<!-- Generated by scripts/migrate/import-cases.mjs ${IMPORTER_VERSION}. Do not edit; run \`npm run migrate:cases\`. -->`,
    `Source: \`${LEGACY_REPOSITORY}\` at \`${model.revision}\` (read-only, extracted with \`git archive\`; the fixture generators are run over that extraction and each generated corpus is checked against the legacy hash manifest).`,
    "This report is generated with the records. It lists what was imported, how, and what was not: dropped, ambiguous or lossy legacy fields, with counts. It is part of the traceability for issue #4 (part of #1). The reasoning is in `docs/decisions/0005-cases-and-fixture-sets.md`.",
  );

  push(
    "## Summary",
    table(
      ["Result", "Count"],
      [
        ["legacy fixtures read", n(c("legacy:fixtures"))],
        ["fixture projections written (all legacy fixtures)", n(fixturesTotal)],
        ["cases written (`records/cases/`)", n(c("records:case"))],
        ["fixture sets written (`records/fixtures/`, one per legacy suite)", n(c("records:fixture-set"))],
        ["authored fixtures (hand-written literal content)", n(c("fixtures:authored"))],
        ["generated fixtures (recorded output of a legacy generation rule)", n(c("fixtures:generated"))],
        ["distinct families referenced by at least one case", `${n(famUsed.size)} of ${n(famAll.length)}`],
        ["cases with historical incidents", n(c("cases:with-incidents"))],
      ],
    ),
    `Records: \`records/cases/<suite>/<case>.json\` (${n(c("records:case"))} files, ${kib(bytesOf("records/cases/"))} KiB) and \`records/fixtures/<suite>.json\` (${n(c("records:fixture-set"))} files, ${kib(bytesOf("records/fixtures/"))} KiB, ${kib(c("fixtures:content-bytes"))} KiB of fixture text). Fixture content is embedded in the set, one line per fixture, so the whole projection layer is ${n(c("records:fixture-set"))} files instead of ${n(fixturesTotal)}.`,
    `Materialization digest: the fixtures materialize (\`npm run fixtures:materialize\`) to a file tree and manifest with materialization digest: \`${digest}\`. \`npm run fixtures:materialize -- --check\` verifies it.`,
  );

  push(
    "## Suites",
    "One fixture set per legacy suite. A suite is either *authored* (hand-written literal fixtures in a committed corpus) or *generated* (the recorded output of generator code in the legacy repository, reproduced byte for byte from the pinned revision and verified against the legacy `generated-corpora.json` hash).",
    table(
      ["Suite", "Origin", "Fixtures", "Cases", "Reproduces legacy hash"],
      model.suiteInfo.map((s) => [
        `\`${s.suite}\``,
        s.generated ? "generated" : "authored",
        n(s.fixtures),
        n(s.cases),
        s.generated ? (model.reproduction[s.suite]?.matches ? "yes" : "NO") : "n/a (committed corpus)",
      ]),
    ),
  );

  push(
    "## Case model",
    "A case is one scenario with one expected outcome and one evidence basis. The importer builds it from the legacy suite structure: every fixture of one suite that shares a shape (or hand-named group), a role (positive base, one-property twin, benign control) and an evidence tier is one case, and each of those fixtures is one projection of it.",
    table(["Case type", "Cases"], withPrefix("case-type:").map(([k, v]) => [`\`${k}\``, n(v)])),
    table(["Expected outcome", "Cases", "Fixtures"], ["must-flag", "must-not-flag", "not-assertable"].map((o) => [`\`${o}\``, n(c(`case-outcome:${o}`)), n(c(`fixture-outcome:${o}`))])),
    table(["Evidence basis", "Cases"], withPrefix("basis:").filter(([k]) => !k.startsWith("downgrade:")).map(([k, v]) => [`\`${k}\``, n(v)])),
    `Wording: ${n(c("wording:hand-written-group"))} cases use hand-written topic, scenario and importance text for a named legacy group (\`scripts/migrate/lib/case-narratives.mjs\`); ${n(c("wording:templated"))} are worded from role templates plus the family names. Both kinds state the expected outcome in scanner-neutral terms.`,
  );

  push(
    "## Legacy assessment to canonical expectation",
    "Outcome comes from the legacy assessment kind and, for `policy`, from whether the fixture has expected spans. The basis comes from the tier (T1 `provider-documented`, T2 `tool-corroborated`, T3 `project-policy`, T0 `unresolved`) with the same mechanical tightening as the taxonomy import.",
    table(["Legacy kind / tier", "Canonical outcome", "Fixtures"], withPrefix("map:").map(([k, v]) => { const [from, to] = k.split(" -> "); return [`\`${from}\``, `\`${to}\``, n(v)]; })),
    table(
      ["Basis change", "Cases"],
      [
        ["T2 recorded as `project-policy`: cited sources do not include two distinct owners", n(c("basis:downgrade:T2-fewer-than-two-owners"))],
        ["T1 recorded below `provider-documented`: no cited source is provider-owned", n(c("basis:downgrade:T1-without-provider-source"))],
      ],
    ),
    "T0 fixtures were unscored in the legacy benchmark, so they become `not-assertable` and their candidate spans are dropped. Cases in `unresolved` never carry a must-flag or must-not-flag expectation.",
  );

  push(
    "## Coverage of the required scenario themes",
    "Cross-provider themes are `scenarios` tags on cases; a case may carry several.",
    table(["Theme", "Cases", "Meaning"], withPrefix("theme:").map(([k, v]) => [`\`${k}\``, n(v), model.themes[k] ?? ""])),
    `Cases involving more than one family are typed \`cross-family\` (${n(c("case-type:cross-family"))}); ${n(c("cases:unscoped"))} cases involve no family and give an \`unscopedReason\`.`,
  );

  push(
    "## Lineage",
    table(
      ["Lineage", "Count"],
      [
        ["twin fixtures with a `twin-of` fixture lineage (all resolved inside their suite)", n(c("lineage:twin-fixtures"))],
        ["metamorphic pairs in legacy data", "0 (the legacy corpus has twins and mutation kinds only; the model supports `metamorphic-of` when they exist)"],
        ...withPrefix("lineage:mutation-kind:").map(([k, v]) => [`mutation kind \`${k}\``, n(v)]),
      ],
    ),
    "Twin cases carry `relations: [{ type: \"twin-of\", target, mutationKind }]` to the positive case; each twin fixture carries `lineage.of` to the exact positive fixture and the legacy mutation note. Generated fixtures are never canonical: they record the generator, its source revision and entrypoint, and their cases are the inputs (`origin.type: generation-rule`).",
  );

  push(
    "## Historical incidents",
    table(
      ["Legacy known-gap data", "Count"],
      [
        ["known-gap issues read", n(c("known-gaps:issues"))],
        ...withPrefix("known-gaps:kind:").map(([k, v]) => [`kind \`${k}\``, n(v)]),
        ["case incident attachments written", n(c("known-gaps:case-attachments"))],
      ],
    ),
    "Each issue becomes an `incidents[]` entry on every case that owns one of its fixtures: a scanner-neutral failure mode (`false-alarm`, `missed-credential`), the issue title as the summary, the date it was first observed, and the product issue as an `externalRefs` pointer. Product workflow (status, fix commit, promotion, candidate build) and the recorded scanner findings are not imported.",
  );

  const dropped = withPrefix("dropped:");
  push(
    "## Dropped, collapsed and lossy",
    "Nothing below is silently lost: each row is a legacy field or fact that the canonical model does not represent, with how many times it occurred.",
    table(
      ["Legacy field or fact", "Count", "Why"],
      [
        ["`fixture-detectors.json` entries (detector assignments per fixture)", n(c("dropped:fixture-detectors-json-entries")), "Scanner/product mapping, not evidence. Detector names are never canonical identity."],
        ["fixture `detectors` (in corpora)", n(c("dropped:fixture-detector-assignment")), "Same as above."],
        ["fixture `arrivalTargets`", n(c("dropped:fixture-arrival-targets")), "Product arrival-family scoring targets."],
        ["`assessment.contract` (detector-keyed contract id)", n(c("dropped:assessment-contract-detector-key")), "Detector key; the family and its format contract come from the fixture index instead."],
        ["fixture `expectedAction` (redact/warn)", n(c("dropped:fixture-expected-action")), "Product policy action, not a semantic outcome."],
        ["fixture `policyFamily`, `policyConformance`", n(c("dropped:fixture-policy-family")), "Product qualification bookkeeping."],
        ["fixture `formatReason`", n(c("dropped:fixture-format-reason-duplicate")), "Duplicate of `assessment.reason`."],
        ["fixture-index `provenance.milestone` / `release`", `${n(c("dropped:fixture-provenance-milestone"))} / ${n(c("dropped:fixture-provenance-release"))}`, "Product release bookkeeping."],
        ["`assessment.reason` variants collapsed to the most frequent one per case", n(c("collapsed:assessment-reason-variants")), "A case has one expectation rationale; the other wordings are per-fixture repetitions (mostly \"Negative twin of <fixture>: ...\")."],
        ["T0 fixtures' candidate spans", `${n(c("dropped:t0-candidate-spans"))} in ${n(c("dropped:t0-fixtures-with-spans"))} fixtures`, "Unscored and unresolved in legacy; `not-assertable` carries no spans."],
        ["companion spans on must-not-flag fixtures", n(c("dropped:companion-span-on-must-not-flag")), "A companion span means \"redacting is accepted, never required\"; a must-not-flag fixture has no spans in the canonical model."],
        ["boilerplate span notes", n(c("dropped:span-boilerplate-note")), "The standard synthetic-value sentence, already implied by the safety rule."],
        ["assessment sources with no evidence-source record", n(c("dropped:assessment-source-not-in-taxonomy-import")), `Project-owned URLs (${R.list("dropped:assessment-source-not-in-taxonomy-import").map((u) => `\`${u}\``).join(", ") || "none"}) that the taxonomy import did not carry.`],
        ["suite `references`, `milestoneReview`", `${n(c("dropped:suite-references"))} / ${n(c("dropped:suite-milestoneReview"))}`, "Release-review bookkeeping."],
        ["known-gap product workflow: status (`fixed` / `verified` / `policy-decision`)", `${n(c("dropped:known-gap-status:fixed"))} / ${n(c("dropped:known-gap-status:verified"))} / ${n(c("dropped:known-gap-status:policy-decision"))}`, "Product lifecycle, not evidence."],
        ["known-gap product workflow: fix, promotion, candidate build, verification, disposition", `${n(c("dropped:known-gap-fix"))} / ${n(c("dropped:known-gap-promotion"))} / ${n(c("dropped:known-gap-candidate-build"))} / ${n(c("dropped:known-gap-verification"))} / ${n(c("dropped:known-gap-disposition"))}`, "Product workflow and release state."],
        ["known-gap recorded scanner findings (expected vs actual rows)", n(c("dropped:known-gap-scanner-evidence-rows")), "Scanner output is an observation for downstream repositories, never evidence."],
        ["known-gap fixtures in suites outside the imported set", n(c("dropped:known-gap-fixture-outside-imported-suites")), `Fixtures of legacy suites that are not part of this import (${R.list("dropped:known-gap-fixture-outside-imported-suites").map((u) => `\`${u}\``).join(", ") || "none"}); ${n(c("known-gaps:issues-without-imported-fixture"))} issue(s) have no imported fixture and therefore no incident.`],
      ].filter((r) => r[1] !== "0" && r[1] !== "0 / 0"),
    ),
    `Also not imported: \`supportStatus\`, scores and ledger rows (never in these files). Free text is truncated to the 2,000-character schema limit when needed: ${n(c("truncated:expectation-rationale") + c("truncated:suite-description") + c("truncated:suite-notes") + c("truncated:incident-summary"))} truncation(s).`,
  );

  push(
    "## Families",
    `${n(famUsed.size)} of ${n(famAll.length)} taxonomy families are referenced by at least one case. ${n(unused.length)} are not: ${unused.length ? unused.map((f) => `\`${f}\``).join(", ") : "none"}. They have contracts and sources (#3) but no legacy fixture exercised them.`,
  );

  push(
    "## Determinism and reproduction",
    "The importer runs the legacy generators (`fixtures/generated/build.mjs`) in a child process over the pinned `git archive`, checks each corpus's SHA-256 against `benchmarks/generated-corpora.json`, and refuses to import on any mismatch. Case ids, ordering and wording are pure functions of that input and of the committed taxonomy records (#3). `npm run migrate:cases:check` regenerates in memory and compares every owned file and this report.",
  );

  return `${out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}
