// Deterministic Markdown migration report for the legacy import (docs/migration/cases-report.md).
// Same input revision => byte-identical output. Counts come from the import itself;
// nothing here is hand-edited. The reclassification itself is reported in
// docs/migration/reclassification-report.md.

import { IMPORTER_VERSION } from "./build-records.mjs";
import { cmp } from "./legacy-model.mjs";
import { LEGACY_REPOSITORY } from "./legacy-source.mjs";

const n = (x) => String(x).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
const row = (...cells) => `| ${cells.join(" | ")} |`;
const table = (head, rows) => [row(...head), row(...head.map(() => "---")), ...rows.map((r) => row(...r))].join("\n");

export function renderCasesReport({ model, built, digest }) {
  const R = model.tally;
  const c = (k) => R.get(k);
  const withPrefix = (prefix) => R.withPrefix(prefix);
  const bytesOf = (prefix) => [...built.files].filter(([p]) => p.startsWith(prefix)).reduce((s, [, t]) => s + Buffer.byteLength(t), 0);
  const kib = (b) => n(Math.round(b / 1024));
  const out = [];
  const push = (...lines) => out.push(...lines.flatMap((l) => [l, ""]));
  const { records } = built;
  const famUsed = new Set([...records.cases.flatMap((x) => x.families.map((f) => f.family)), ...model.fx.flatMap((e) => e.families)]);
  const famAll = [...model.taxonomyFamilies.keys()].sort(cmp);
  const unused = famAll.filter((f) => !famUsed.has(f));
  const fixturesTotal = c("fixtures:generated") + c("fixtures:authored");

  push(
    "# Cases and fixtures import report",
    `<!-- Generated by scripts/migrate/import-cases.mjs ${IMPORTER_VERSION}. Do not edit; run \`npm run migrate:cases\`. -->`,
    `Source: \`${LEGACY_REPOSITORY}\` at \`${model.revision}\` (read-only, extracted with \`git archive\`; the fixture generators are run over that extraction and each generated corpus is checked against the legacy hash manifest).`,
    "This report is generated with the records. It lists what the reclassifying importer wrote and what it did not carry: dropped, ambiguous or lossy legacy fields, with counts. Which legacy case became what, and why, is in `docs/migration/reclassification-report.md`. The reasoning is in `docs/decisions/0005-cases-and-fixture-sets.md`, `0007` and `0008`.",
  );

  push(
    "## Summary",
    table(
      ["Result", "Count"],
      [
        ["legacy fixtures read", n(c("legacy:fixtures"))],
        ["fixtures written (all legacy fixtures)", n(fixturesTotal)],
        ["scenarios written (`records/scenarios/`)", n(c("records:scenario"))],
        ["cases written (`records/cases/`)", n(c("records:case"))],
        ["fixture plans written (`records/fixture-plans/`)", n(c("records:fixture-plan"))],
        ["fixture sets written (`records/fixtures/`, by provider)", n(c("records:fixture-set"))],
        ["legacy-map shards written (`migration/legacy-map/`, one per legacy suite)", n(c("records:legacy-map"))],
        ["legacy-map entries (suites, imported cases and fixtures)", n(c("map:entries"))],
        ["authored fixtures (hand-written literal content)", n(c("fixtures:authored"))],
        ["generated fixtures (recorded output of a legacy generation rule)", n(c("fixtures:generated"))],
        ["evidence entries (shared by fixtures)", n(c("evidence:entries"))],
        ["families referenced by a case or a cell", `${n(famUsed.size)} of ${n(famAll.length)}`],
        ["cases with historical incidents", n(c("cases:with-incidents"))],
      ],
    ),
    `Size: \`records/cases/\` ${n(c("records:case"))} files, ${kib(bytesOf("records/cases/"))} KiB; \`records/scenarios/\` ${kib(bytesOf("records/scenarios/"))} KiB; \`records/fixture-plans/\` ${kib(bytesOf("records/fixture-plans/"))} KiB; \`records/fixtures/\` ${n(c("records:fixture-set"))} files, ${kib(bytesOf("records/fixtures/"))} KiB (${kib(c("fixtures:content-bytes"))} KiB of fixture text); \`migration/legacy-map/\` ${kib(bytesOf("migration/legacy-map/"))} KiB.`,
    `Materialization digest: the fixtures materialize (\`npm run fixtures:materialize\`) to a file tree and manifest with materialization digest: \`${digest}\`. \`npm run fixtures:materialize -- --check\` verifies it.`,
  );

  push(
    "## Fixture sets",
    "Sets are organised by the provider of the fixture's family (`provider-neutral` when it has none, `cross-provider` when it spans several). Authored and generated content are never mixed: authored sets carry the `authored-` prefix. A set is derived data; its fixtures project a Case or a fixture-plan cell and each carries its own evidence entry.",
    table(
      ["Set", "Origin", "Fixtures", "Evidence entries"],
      records.sets.map((s) => [`\`${s.id}\``, s.generated ? "generated" : "authored", n(s.fixtures.length), n(Object.keys(s.evidence).length)]),
    ),
  );

  push(
    "## Outcomes and evidence",
    table(["Expected outcome", "Fixtures"], ["must-flag", "must-not-flag", "not-assertable"].map((o) => [`\`${o}\``, n(c(`fixture-outcome:${o}`))])),
    "Outcome comes from the legacy assessment kind and, for `policy`, from whether the fixture has expected spans. The basis comes from the tier (T1 `provider-documented`, T2 `tool-corroborated`, T3 `project-policy`, T0 `unresolved`) with the same mechanical tightening as the taxonomy import; it is carried by each fixture's evidence entry, never by an id.",
    table(["Legacy kind / tier", "Canonical outcome", "Fixtures"], withPrefix("map:").filter(([k]) => k.includes(" -> ")).map(([k, v]) => { const [from, to] = k.split(" -> "); return [`\`${from}\``, `\`${to}\``, n(v)]; })),
    table(
      ["Basis change", "Fixtures"],
      [
        ["T2 recorded as `project-policy`: cited sources do not include two distinct owners", n(c("basis:downgrade:T2-fewer-than-two-owners"))],
        ["T1 recorded below `provider-documented`: no cited source is provider-owned", n(c("basis:downgrade:T1-without-provider-source"))],
      ],
    ),
    `T0 fixtures were unscored in the legacy benchmark, so they become \`not-assertable\`. Their candidate spans are kept as non-asserting data (\`candidateReading\`, \`asserting: false\`; ADR 0012 decision 2), never as expected spans: ${n(c("kept:t0-candidate-spans"))} spans in ${n(c("kept:t0-fixtures-with-candidate"))} fixtures. Evidence in \`unresolved\` never carries a must-flag or must-not-flag expectation.`,
    `Per-fixture family override (ADR 0012 decision 4): ${n(c("fixtures:families-override"))} fixtures of Cases that span several families carry their own narrower \`families\` list, which removes ${n(c("fixtures:families-override-links-removed"))} family links the Case-level union would otherwise give them. The Cases are unchanged.`,
  );

  push(
    "## Lineage",
    table(
      ["Lineage", "Count"],
      [
        ["twin fixtures with a `twin-of` fixture lineage (all resolved inside their legacy suite, re-keyed to canonical fixture ids)", n(c("lineage:twin-fixtures"))],
        ["metamorphic pairs in legacy data", "0 (the legacy corpus has twins and mutation kinds only; the model supports `metamorphic-of` when they exist)"],
        ...withPrefix("lineage:mutation-kind:").map(([k, v]) => [`mutation kind \`${k}\``, n(v)]),
      ],
    ),
    "Each twin fixture carries `lineage.of` to the exact positive fixture and the legacy mutation note. Generated fixtures are never canonical: the set records the generator, its source revision and entrypoint.",
  );

  push(
    "## Historical incidents",
    table(
      ["Legacy known-gap data", "Count"],
      [
        ["known-gap issues read", n(c("known-gaps:issues"))],
        ...withPrefix("known-gaps:kind:").map(([k, v]) => [`kind \`${k}\``, n(v)]),
        ["incident attachments on Cases", n(c("cases:with-incidents"))],
        ["fixtures carrying incidents directly (matrix cells)", n(c("fixtures:with-incidents"))],
      ],
    ),
    "Each issue becomes an `incidents[]` entry on the Case that owns one of its fixtures, or on the fixture itself when the fixture is a matrix cell: a scanner-neutral failure mode (`false-alarm`, `missed-credential`), the issue title as the summary, the date first observed, and the product issue as an `externalRefs` pointer. Product workflow (status, fix commit, promotion, candidate build) and the recorded scanner findings are not imported.",
  );

  push(
    "## Dropped, collapsed and lossy",
    "Nothing below is silently lost: each row is a legacy field or fact that the canonical model does not represent, with how many times it occurred.",
    table(
      ["Legacy field or fact", "Count", "Why"],
      [
        ["`fixture-detectors.json` entries (detector assignments per fixture)", n(c("dropped:fixture-detectors-json-entries")), "Scanner/product mapping, not evidence. Detector names are never canonical identity."],
        ["fixture `detectors` (in corpora)", n(c("dropped:fixture-detector-assignment")), "Same as above."],
        ["fixture `arrivalTargets`", n(c("dropped:fixture-arrival-targets")), "Product arrival-family scoring targets."],
        ["`assessment.contract` (detector-keyed contract id)", n(c("dropped:assessment-contract-detector-key")), "Detector key; the family and its format contract come from the fixture index instead."],
        ["fixture `expectedAction` (redact/warn)", n(c("dropped:fixture-expected-action")), "Product policy action, not a semantic outcome."],
        ["fixture `policyFamily`, `policyConformance`", n(c("dropped:fixture-policy-family")), "Product qualification bookkeeping."],
        ["fixture `formatReason`", n(c("dropped:fixture-format-reason-duplicate")), "Duplicate of `assessment.reason`."],
        ["fixture-index `provenance.milestone` / `release`", `${n(c("dropped:fixture-provenance-milestone"))} / ${n(c("dropped:fixture-provenance-release"))}`, "Product release bookkeeping."],
        ["`assessment.reason` variants collapsed to the most frequent one per evidence entry", n(c("collapsed:assessment-reason-variants")), "Repetitions only: the per-fixture \"Negative twin of <positive>: ...\" renderings of one twin template share an entry. Of the 875 variants the first import collapsed, 840 were such repetitions."],
        ["`assessment.reason` variants kept as their own evidence entry (distinct reasons)", n(c("split:assessment-reason-distinct")), "A reason that is not a twin repetition (a placeholder control next to a policy-floor control, a relabelling note, a per-family contract wording) is cited by its own fixtures instead of being overwritten by the most frequent wording (issue #76, ADR 0014)."],
        ["first-import case prose of template-worded cases (titles, summaries, rationales)", n(model.classificationCounts.projection), "Generated from role templates plus family names; the reasoning each states is now one Scenario, written once. See the reclassification report."],
        ["first-import `twin-of` relations between cases", n(model.classificationCounts.twinCases), "A property of the legacy groups; the twin groups are scenario cells now. Fixture-level lineage is kept."],
        ["companion spans on must-not-flag fixtures", n(c("dropped:companion-span-on-must-not-flag")), "A companion span means \"redacting is accepted, never required\"; a must-not-flag fixture has no spans in the canonical model."],
        ["boilerplate span notes", n(c("dropped:span-boilerplate-note")), "The standard synthetic-value sentence, already implied by the safety rule."],
        ["assessment sources with no evidence-source record", n(c("dropped:assessment-source-not-in-taxonomy-import")), `Project-owned URLs (${R.list("dropped:assessment-source-not-in-taxonomy-import").map((u) => `\`${u}\``).join(", ") || "none"}) that the taxonomy import did not carry.`],
        ["known-gap product workflow: status (`fixed` / `verified` / `policy-decision`)", `${n(c("dropped:known-gap-status:fixed"))} / ${n(c("dropped:known-gap-status:verified"))} / ${n(c("dropped:known-gap-status:policy-decision"))}`, "Product lifecycle, not evidence."],
        ["known-gap product workflow: fix, promotion, candidate build, verification, disposition", `${n(c("dropped:known-gap-fix"))} / ${n(c("dropped:known-gap-promotion"))} / ${n(c("dropped:known-gap-candidate-build"))} / ${n(c("dropped:known-gap-verification"))} / ${n(c("dropped:known-gap-disposition"))}`, "Product workflow and release state."],
        ["known-gap recorded scanner findings (expected vs actual rows)", n(c("dropped:known-gap-scanner-evidence-rows")), "Scanner output is an observation for downstream repositories, never evidence."],
        ["known-gap fixtures in suites outside the imported set", n(c("dropped:known-gap-fixture-outside-imported-suites")), `Fixtures of legacy suites that are not part of this import (${R.list("dropped:known-gap-fixture-outside-imported-suites").map((u) => `\`${u}\``).join(", ") || "none"}); ${n(c("known-gaps:issues-without-imported-fixture"))} issue(s) have no imported fixture and therefore no incident.`],
      ].filter((r) => r[1] !== "0" && r[1] !== "0 / 0"),
    ),
    `Also not imported: \`supportStatus\`, scores and ledger rows (never in these files). Free text is truncated to the 2,000-character schema limit when needed: ${n(c("truncated:evidence-rationale") + c("truncated:set-notes") + c("truncated:incident-summary"))} truncation(s).`,
  );

  push(
    "## Families",
    `${n(famUsed.size)} of ${n(famAll.length)} taxonomy families are referenced by at least one case or fixture cell. ${n(unused.length)} are not: ${unused.length ? unused.map((f) => `\`${f}\``).join(", ") : "none"}. They have contracts and sources (#3) but no legacy fixture exercised them.`,
  );

  push(
    "## Determinism and reproduction",
    "The importer runs the legacy generators (`fixtures/generated/build.mjs`) in a child process over the pinned `git archive`, checks each corpus's SHA-256 against `benchmarks/generated-corpora.json`, and refuses to import on any mismatch. Canonical ids, ordering and wording are pure functions of that input, of the committed taxonomy records (#3) and of the authored tables. `npm run migrate:cases:check` regenerates in memory and compares every owned file and the reports.",
  );

  return `${out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}
