// Renders docs/migration/narrative-report.md: every legacy dossier accounted for as
// migrated, partial or deferred, with statement and citation counts (issue #16, ADR 0010).

import { createHash } from "node:crypto";
import { readdirSync } from "node:fs";
import { join } from "node:path";
import YAML from "yaml";
import { LEGACY_PATHS, LEGACY_REPOSITORY, readLegacyText } from "./legacy-source.mjs";
import { GENERATOR, SECTION_ORDER } from "./narrative-build.mjs";

const cmp = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
const fmt = (n) => n.toLocaleString("en-US");
const bytes = (s) => Buffer.byteLength(s);

/** One row per legacy dossier file: provider, families, body size, and the prose labels it carries. */
export function inventoryDossiers(root) {
  const dir = join(root, LEGACY_PATHS.dossierDir);
  const out = [];
  for (const name of readdirSync(dir).sort(cmp)) {
    if (!name.endsWith(".md") || name === "README.md" || name.startsWith("_")) continue;
    const path = `${LEGACY_PATHS.dossierDir}/${name}`;
    const text = readLegacyText(root, path);
    const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(text);
    if (!m) throw new Error(`${path}: no YAML frontmatter`);
    const front = YAML.parse(m[1]);
    const body = m[2];
    out.push({
      path,
      provider: front.provider,
      families: front.families.map((f) => ({ id: f.id, verdict: f.research.verdict, tier: f.research.tier ?? null })),
      bodyBytes: bytes(body),
      bodySha256: createHash("sha256").update(body).digest("hex"),
      contractLinks: (body.match(/^- \*\*Current contract in core:\*\*/gm) ?? []).length,
      logEntries: (body.split(/^## Research log$/m)[1] ?? "").split(/\n(?=- )/).filter((l) => l.startsWith("- ")).length,
      candidateItems: (body.split(/^## Candidates that are not families yet$/m)[1] ?? "").split(/^## /m)[0].split(/\n(?=- )/).filter((l) => l.startsWith("- ")).length,
    });
  }
  return out;
}

const countBy = (items, key) => {
  const m = new Map();
  for (const i of items) m.set(key(i), (m.get(key(i)) ?? 0) + 1);
  return m;
};

function statementStats(narratives) {
  const s = { statements: 0, citations: 0, claimCitations: 0, sourceCitations: 0, unresolved: 0, text: 0, byClass: new Map(), bySection: new Map() };
  for (const n of narratives) {
    for (const [section, list] of Object.entries(n.sections)) {
      for (const st of list) {
        s.statements += 1;
        s.text += bytes(st.text);
        s.byClass.set(st.evidenceClass, (s.byClass.get(st.evidenceClass) ?? 0) + 1);
        s.bySection.set(section, (s.bySection.get(section) ?? 0) + 1);
        if (st.unresolved) s.unresolved += 1;
        for (const c of st.citations ?? []) {
          s.citations += 1;
          if (c.kind === "claim") s.claimCitations += 1;
          else s.sourceCitations += 1;
        }
      }
    }
  }
  return s;
}

export function renderNarrativeReport({ inventory, rows, dropped, legacyRevision, deferredReason }) {
  const byFamily = new Map(rows.map((r) => [r.id, r]));
  const inventoryFamilies = inventory.flatMap((d) => d.families.map((f) => ({ ...f, provider: d.provider })));
  for (const r of rows) if (!inventoryFamilies.some((f) => f.id === r.id)) throw new Error(`authored family '${r.id}' is in no legacy dossier`);

  const dossiers = inventory.map((d) => {
    const fam = d.families.map((f) => byFamily.get(f.id));
    const done = fam.filter(Boolean);
    const migrated = done.filter((r) => r.status === "migrated").length;
    const status = !done.length ? "deferred" : migrated === d.families.length ? "migrated" : "partial";
    const stats = statementStats(done.map((r) => r.narrative));
    return { ...d, status, authored: done.length, stats };
  });
  const famStatus = (id) => byFamily.get(id)?.status ?? "deferred";
  const famCounts = countBy(inventoryFamilies, (f) => famStatus(f.id));
  const dossCounts = countBy(dossiers, (d) => d.status);
  const all = statementStats(rows.map((r) => r.narrative));
  const bodyTotal = inventory.reduce((n, d) => n + d.bodyBytes, 0);
  const bodyDone = dossiers.filter((d) => d.authored).reduce((n, d) => n + d.bodyBytes, 0);
  const carried = dossiers.filter((d) => d.authored);
  const lines = [];
  const push = (...l) => lines.push(...l);

  push(
    "# Narrative migration report",
    "",
    `<!-- Generated by scripts/migrate/${GENERATOR.split(" ")[0]}.mjs ${GENERATOR.split(" ")[1]}. Do not edit; run \`npm run migrate:narratives\`. -->`,
    "",
    `Source: \`${LEGACY_REPOSITORY}\` at \`${legacyRevision}\` (read-only). Part of issue #16 (part of #1); the model is ADR 0010.`,
    "",
    "The taxonomy import (#3) kept the markdown bodies of the legacy dossiers out of the canonical model, because copying free prose would be hand-authored evidence without traceability (ADR 0004). This report records the rewrite: each family narrative is authored by a person in scanner-neutral language, every statement cites a contract claim or an evidence source, and a statement with neither is `unresolved` and points at a review event. Nothing is copied verbatim. This repository is maintained by the Redact Secret project; its narratives are project-authored and are not independent validation.",
    "",
    "## Summary",
    "",
    "| Measure | Value |",
    "| --- | --- |",
    `| legacy dossiers | ${inventory.length} |`,
    `| dossiers migrated / partial / deferred | ${dossCounts.get("migrated") ?? 0} / ${dossCounts.get("partial") ?? 0} / ${dossCounts.get("deferred") ?? 0} |`,
    `| legacy families | ${inventoryFamilies.length} |`,
    `| families migrated / partial / deferred | ${famCounts.get("migrated") ?? 0} / ${famCounts.get("partial") ?? 0} / ${famCounts.get("deferred") ?? 0} |`,
    `| legacy dossier body bytes | ${fmt(bodyTotal)} |`,
    `| body bytes of dossiers with at least one narrative | ${fmt(bodyDone)} |`,
    `| narrative records | ${rows.length} (all \`draft\`) |`,
    `| statements | ${all.statements} (${fmt(all.text)} bytes of text) |`,
    `| citations | ${all.citations} (${all.claimCitations} to contract claims, ${all.sourceCitations} to evidence sources) |`,
    `| unresolved statements | ${all.unresolved}, each with a review event |`,
    "",
    "Statements by section:",
    "",
    "| Section | Statements |",
    "| --- | --- |",
    ...SECTION_ORDER.map((s) => `| \`${s}\` | ${all.bySection.get(s) ?? 0} |`),
    "",
    "Statements by evidence class:",
    "",
    "| Evidence class | Statements |",
    "| --- | --- |",
    ...["provider-documented", "tool-corroborated", "project-policy", "unresolved"].map((c) => `| \`${c}\` | ${all.byClass.get(c) ?? 0} |`),
    "",
    "## Definitions",
    "",
    "- **migrated**: every family of the dossier has a narrative that restates the dossier's shape, issuance, collision and open-question content, or records it as unresolved.",
    "- **partial**: at least one family has a narrative and at least one has none, or a narrative states in its `notes` what it leaves out.",
    "- **deferred**: no family of the dossier has a narrative yet. The reason is given per dossier.",
    "",
    "Every narrative is `draft`. Promotion to `reviewed` needs a reviewer who did not author it (`docs/governance/attribution.md`) and is a separate, human step; the validator refuses a `reviewed` narrative without one.",
    "",
    "## Content that is not carried, by design",
    "",
    "These parts of a dossier body are not narrative and are not rewritten. They are counted here so that omitting them is visible.",
    "",
    "| Dossier part | Why it is not a narrative statement | Occurrences in migrated or partial dossiers |",
    "| --- | --- | --- |",
    `| \`Current contract in core\` links | how a product detects the family: product policy, not credential knowledge | ${carried.reduce((n, d) => n + d.contractLinks, 0)} |`,
    `| \`Research log\` entries | issue and pull-request workflow; the research state is \`family.research\` and the issue numbers are \`family.research.issues\` | ${carried.reduce((n, d) => n + d.logEntries, 0)} |`,
    `| \`Candidates that are not families yet\` | not a family and not carried as statements; where a candidate bears on a family (for example the ABIA and ACCA prefixes) that family's narrative covers it, and the rest is listed below | ${carried.reduce((n, d) => n + d.candidateItems, 0)} |`,
    "| `Verdict` lines | re-expressed as `family.research` and the review history by the taxonomy import (#3) | n/a |",
    "| `Sources` lines | replaced by per-statement citations | n/a |",
    "",
    "### Specific dossier content that is not carried",
    "",
    "Content of a migrated dossier that is neither carried as a statement nor one of the parts above. Each stays at the pinned legacy path.",
    "",
    "| Dossier | Part | Why it is not carried |",
    "| --- | --- | --- |",
    ...dropped.map((d) => `| \`${d.provider}\` | ${d.part} | ${d.reason} |`),
    "",
    "## Dossiers",
    "",
    "| Dossier | Families | Status | Narratives | Statements | Citations | Unresolved | Body bytes |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ...dossiers.map((d) => `| \`${d.provider}\` | ${d.families.length} | ${d.status} | ${d.authored} | ${d.stats.statements} | ${d.stats.citations} | ${d.stats.unresolved} | ${fmt(d.bodyBytes)} |`),
    "",
    "### Deferred",
    "",
    deferredReason,
    "",
    `Deferred dossiers (${dossCounts.get("deferred") ?? 0}): ${dossiers.filter((d) => d.status === "deferred").map((d) => `\`${d.provider}\``).join(", ") || "none"}.`,
    "",
    "### Migrated and partial families",
    "",
    "| Family | Status | Statements | Cited | Unresolved | Notes |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows
      .slice()
      .sort((a, b) => cmp(a.id, b.id))
      .map((r) => {
        const st = statementStats([r.narrative]);
        return `| \`${r.id}\` | ${r.status} | ${st.statements} | ${st.statements - st.unresolved} | ${st.unresolved} | ${r.note ?? ""} |`;
      }),
    "",
    "### Families in deferred or partial dossiers",
    "",
    "| Family | Dossier verdict | Status |",
    "| --- | --- | --- |",
    ...inventoryFamilies
      .filter((f) => famStatus(f.id) === "deferred")
      .map((f) => `| \`${f.id}\` | ${f.verdict}${f.tier ? ` / ${f.tier}` : ""} | deferred |`),
    "",
  );
  return `${lines.join("\n")}`;
}
