// Deterministic Markdown report of the reclassification of the imported legacy cases
// (docs/migration/reclassification-report.md). Same input revision => byte-identical
// output. Every number comes from the classification and the records built from it.

import { RULES, CARRIER_GROUPS, HAND_AUTHORED_SUITES } from "./classify.mjs";
import { cmp, uniqSorted } from "./legacy-model.mjs";
import { LEGACY_REPOSITORY } from "./legacy-source.mjs";
import { IMPORTER_VERSION } from "./build-records.mjs";

const n = (x) => String(x).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
const row = (...cells) => `| ${cells.join(" | ")} |`;
const table = (head, rows) => [row(...head), row(...head.map(() => "---")), ...rows.map((r) => row(...r))].join("\n");
const code = (x) => `\`${x}\``;
const pct = (a, b) => `${((100 * a) / b).toFixed(1)}%`;

export function renderReclassificationReport({ model, built, before }) {
  const { aggs, fx, revision } = model;
  const { classification, records, caseInfo } = built;
  const out = [];
  const push = (...lines) => out.push(...lines.flatMap((l) => [l, ""]));
  const cls = (a) => classification.get(a.key);
  const byClass = { case: [], scenario: [], projection: [] };
  for (const a of aggs) byClass[cls(a).cls].push(a);
  const fxOf = (list) => list.reduce((s, a) => s + a.entries.length, 0);

  push(
    "# Reclassification of the imported cases",
    `<!-- Generated by scripts/migrate/import-cases.mjs ${IMPORTER_VERSION}. Do not edit; run \`npm run migrate:cases\`. -->`,
    `Source: \`${LEGACY_REPOSITORY}\` at \`${revision}\` (read-only). This is stage B of issue #12 (part of #1). It says, for each of the ${n(aggs.length)} cases the first import (issue #4) wrote, whether it was a genuine Case, a reusable Scenario or a cell of a matrix projection, by which rule, and what the canonical tree looks like as a result. The criteria are ADR 0007 section 3; the decisions that stage B adds are in \`docs/decisions/0008-semantic-tree-and-reclassification.md\`.`,
    "The classification is a pure function of the legacy data and two authored tables (`scripts/migrate/lib/classify.mjs`: carrier groups; `scripts/migrate/authored/cases.mjs`: the groups each hand-written Case carries). There is no per-record decision: the rules below are the decision, and the run fails if a legacy group matches none.",
  );

  push(
    "## Result",
    table(
      ["", "Before (first import)", "After"],
      [
        ["Cases (`records/cases/`)", n(before.cases), `${n(records.cases.length)}`],
        ["Scenarios (`records/scenarios/`)", "0", n(records.scenarios.length)],
        ["Fixture plans (`records/fixture-plans/`)", "0", n(records.plans.length)],
        ["Fixture sets (`records/fixtures/`)", `${n(before.sets)} (one per legacy suite)`, `${n(records.sets.length)} (one per provider, authored and generated apart)`],
        ["Fixtures", n(fx.length), n(fx.length)],
        ["Legacy-map entries (`migration/legacy-map/`)", "0", n(model.tally.get("map:entries"))],
        ["Canonical ids or paths with a legacy coordinate", n(before.violations), "0"],
      ],
    ),
    "The ADR 0007 target was: case count drops to genuine case studies, every fixture stays traceable. Both hold: " +
      `${n(aggs.length)} imported cases become ${n(records.cases.length)} Cases (a ${pct(aggs.length - records.cases.length, aggs.length)} reduction), and ${n(fx.length)} of ${n(fx.length)} fixtures are mapped one to one to a fixture id in \`migration/legacy-map/\`.`,
  );

  push(
    "## What each legacy case became",
    table(
      ["Class", "Legacy cases", "Fixtures", "Becomes", "Canonical records"],
      [
        ["genuine Case", n(byClass.case.length), n(fxOf(byClass.case)), "a Case, with hand-authored prose", `${n(records.cases.length)} Cases (${n(byClass.case.length - records.cases.length)} legacy groups folded into another Case of the same reasoning or tier)`],
        ["reusable Scenario", n(byClass.scenario.length), n(fxOf(byClass.scenario)), "a carrier Scenario; the fixtures are cells of it", `${n(uniqSorted(byClass.scenario.map((a) => cls(a).target.id)).length)} Scenarios`],
        ["matrix projection", n(byClass.projection.length), n(fxOf(byClass.projection)), "cells of a role Scenario; the per-cell prose is dropped", `${n(uniqSorted(byClass.projection.map((a) => cls(a).target.id)).length)} Scenarios`],
        ["total", n(aggs.length), n(fx.length), "", ""],
      ],
    ),
    `The ${n(byClass.projection.length)} matrix projections (${pct(byClass.projection.length, aggs.length)} of the cases, ${n(fxOf(byClass.projection))} fixtures) are the template-worded cells the first import mistook for reasoning units: each was "Family name, role template" and differed from its neighbours only in the family's name, prefix or length.`,
  );

  push(
    "## Rules",
    "Rules are tried in this order; the first that applies decides. A legacy group that no rule covers stops the import.",
    table(
      ["Rule", "Class", "Applies to", "Legacy cases", "Fixtures"],
      RULES.map((r) => {
        const hit = aggs.filter((a) => cls(a).rule === r.id);
        return [code(r.id), r.class, r.title, n(hit.length), n(fxOf(hit))];
      }),
    ),
    ...RULES.flatMap((r) => [`### ${code(r.id)}`, r.justification]),
  );

  // ---- tier and identity
  const tierKeys = new Map();
  for (const a of aggs) {
    const k = [a.suite, a.shape, a.role, a.outcome].join("\u0000");
    if (!tierKeys.has(k)) tierKeys.set(k, []);
    tierKeys.get(k).push(a);
  }
  const split = [...tierKeys.values()].filter((g) => new Set(g.map((a) => a.tier)).size > 1);
  const basisFx = {};
  for (const e of fx) basisFx[e.agg.evidence.basis] = (basisFx[e.agg.evidence.basis] ?? 0) + 1;
  const caseBasis = {};
  for (const i of caseInfo.values()) caseBasis[i.basis] = (caseBasis[i.basis] ?? 0) + 1;
  const mixedCases = [...caseInfo.entries()].filter(([, i]) => new Set(i.aggs.map((a) => a.evidence.basis)).size > 1).map(([id]) => id);
  push(
    "## Evidence tier is not identity",
    `The first import keyed a case on suite, shape, role, outcome **and legacy tier**. ${n(split.length)} of the ${n(tierKeys.size)} keys that differ only in tier were split across two or three cases (${n(split.reduce((s, g) => s + g.length, 0))} cases); those merge: a tier never creates a Case, a Scenario or a plan cell. The tier, re-expressed as an evidence basis, is carried per fixture in the set's \`evidence\` map (with the reason and sources the legacy assessment cited), and a Case or Scenario states only the weakest basis its fixtures share.`,
    table(
      ["Fixtures by evidence basis", "Count"],
      ["provider-documented", "tool-corroborated", "project-policy", "unresolved"].map((b) => [code(b), n(basisFx[b] ?? 0)]),
    ),
    table(
      ["Cases by expectation basis (weakest of their fixtures)", "Count"],
      ["provider-documented", "tool-corroborated", "project-policy", "unresolved"].map((b) => [code(b), n(caseBasis[b] ?? 0)]),
    ),
    `${n(mixedCases.length)} ${mixedCases.length === 1 ? "Case carries" : "Cases carry"} fixtures of more than one basis (${mixedCases.map(code).join(", ") || "none"}); ${mixedCases.length === 1 ? "its" : "their"} fixtures keep their own evidence entries.`,
  );

  // ---- per suite
  const suiteRows = model.suites.map((s) => {
    const list = aggs.filter((a) => a.suite === s);
    const c = (k) => list.filter((a) => cls(a).cls === k).length;
    return [code(s), HAND_AUTHORED_SUITES.has(s) ? "hand-written" : "template-worded", n(list.length), n(c("case")), n(c("scenario")), n(c("projection")), n(list.reduce((t, a) => t + a.entries.length, 0))];
  });
  push(
    "## Per legacy suite",
    "Legacy suite names appear here because this report is a migration record; they are not canonical identity.",
    table(["Legacy suite", "Wording", "Legacy cases", "Case", "Scenario", "Projection", "Fixtures"], suiteRows),
  );

  // ---- genuine cases
  push(
    "## The genuine Cases",
    `${n(records.cases.length)} Cases survive. Each has prose written for exactly the inputs it covers (\`scripts/migrate/authored/cases.mjs\`), an expectation with its own reason, and at least one fixture. "Legacy groups" is how many first-import cases folded into it.`,
    table(
      ["Case", "Outcome", "Basis", "Fixtures", "Legacy groups", "Families"],
      records.cases.map((c) => {
        const i = caseInfo.get(c.id);
        return [code(c.id), code(c.expectation.outcome), code(c.expectation.basis), n(i.fixtures), n(i.aggs.length), n(c.families.length)];
      }),
    ),
    `Criteria applied (ADR 0007 section 3): a failure mode specific to the Case, prose no template could produce, an expectation that no Scenario plus a family list reproduces, its own evidence or an explicit project-policy decision, and a name without a coordinate. Borderline decisions, stated so they can be disputed:`,
    "- The nine carrier groups of the context-edges suite and the four carrier groups of token-contexts are **Scenarios**, not Cases: their narrative is about the carrier, and the same sentence holds for every format. Criterion 3 fails for them.",
    "- Twins (one-property mutations) are **matrix projections** even in hand-written suites (SendGrid, policy-qualified credentials, context-edges, token-contexts): the twin's content is the changed property and the family. The fixture keeps its `twin-of` lineage to the exact positive.",
    "- Milestone regressions, reference-syntax groups and their overlaps fold together: a reasoning unit stated in two suites (code expressions, secret-manager pointers, template expressions, interpolation, literals under generic names) is one Case.",
    "- A positive group and its benign counterpart stay two Cases: a Case has one outcome, and the pairing is the reasoning (the exemption and its boundary).",
  );

  // ---- scenarios
  const cellsOfScenario = new Map();
  for (const e of fx) if (e.cls.target.type === "scenario") {
    const k = e.cls.target.id;
    if (!cellsOfScenario.has(k)) cellsOfScenario.set(k, []);
    cellsOfScenario.get(k).push(e);
  }
  const aggsOfScenario = new Map();
  for (const a of aggs) if (cls(a).target.type === "scenario") {
    const k = cls(a).target.id;
    aggsOfScenario.set(k, (aggsOfScenario.get(k) ?? 0) + 1);
  }
  push(
    "## The Scenarios",
    `${n(records.scenarios.length)} Scenarios, each written once (\`scripts/migrate/authored/scenarios.mjs\`). Two carry no cells: they are cross-cutting themes that Cases reference.`,
    table(
      ["Scenario", "Outcome class", "Plan", "Cells (fixtures)", "Families", "Legacy cases"],
      records.scenarios.map((s) => {
        const cells = cellsOfScenario.get(s.id) ?? [];
        const plan = built.planOfScenario.get(s.id);
        return [code(s.id), code(s.expectedOutcomeClass), plan ? code(plan) : "none", n(cells.length), n(new Set(cells.flatMap((e) => e.families)).size), n(aggsOfScenario.get(s.id) ?? 0)];
      }),
    ),
    `Carrier groups classified as Scenarios: ${Object.entries(CARRIER_GROUPS).map(([k, v]) => `${code(k)} → ${code(v)}`).join("; ")}.`,
  );

  // ---- plans
  push(
    "## The fixture plans",
    "A plan declares which families are instantiated against which Scenarios. The matrix is sparse: the legacy content instantiated only some cells, and the fixtures that project the plan are the record of which.",
    table(
      ["Plan", "Scenarios", "Families", "Cells with fixtures", "Possible cells", "Coverage", "Fixtures", "Output sets"],
      records.plans.map((p) => {
        const cells = built.cellsOfPlan.get(p.id);
        const pairs = new Set(cells.flatMap((e) => e.families.map((f) => `${e.cls.target.id}|${f}`)));
        const possible = p.matrix.targets.length * p.matrix.families.ids.length;
        return [code(p.id), n(p.matrix.targets.length), n(p.matrix.families.ids.length), n(pairs.size), n(possible), pct(pairs.size, possible), n(cells.length), n(p.output.length)];
      }),
    ),
  );

  // ---- traceability, incidents
  const gaps = model.tally;
  push(
    "## Every fixture is traceable",
    `\`migration/legacy-map/<suite>.json\` has one shard per legacy suite (${n(model.suites.length)} shards, ${n(gaps.get("map:entries"))} entries): the suite, each imported case and each fixture, with the canonical record that carries it. No entry is \`dropped\`: nothing was removed. The map is what lets the compatibility exporter regenerate legacy names (stage C) and lets a consumer trace any of the ${n(fx.length)} legacy fixtures. The legacy fixture id of a fixture appears only there.`,
    `Fixture ids are \`<provider>--<name>\`: the provider set plus the legacy fixture name with any migration coordinate removed (${n(gaps.get("fixture-id:coordinate-scrubbed"))} names were scrubbed) and a deterministic suffix when two legacy suites used one name (${n(gaps.get("fixture-id:collision-suffixed"))} collisions).`,
  );
  push(
    "## Incidents and lineage",
    `The ${n(gaps.get("known-gaps:issues"))} known-gap issues of the legacy repository attach to ${n(gaps.get("cases:with-incidents"))} Cases and, for fixtures that are now matrix cells, to ${n(gaps.get("fixtures:with-incidents"))} fixtures directly (\`incidents\` on the set item; a cell has no record of its own to hold them). Twin lineage is fixture level: ${n(gaps.get("lineage:twin-fixtures"))} twin fixtures keep \`lineage.of\` to the exact positive fixture; case-level \`twin-of\` relations were a property of the legacy groups and are not recreated (the twin groups are scenario cells now).`,
  );

  push(
    "## Determinism",
    "`npm run migrate:cases` reads only the pinned legacy revision (through `git archive`, running the legacy generators over that extraction and checking each corpus against the legacy hash manifest) and the committed taxonomy records. `npm run migrate:cases -- --check` regenerates everything in memory and fails on any difference in the owned directories or in this report.",
  );

  return `${out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}
