// Deterministic Markdown migration report for the taxonomy import.
// Same input revision => byte-identical output. Counts come from the import
// itself; nothing here is hand-edited.

import { LEGACY_PATHS, LEGACY_REPOSITORY } from "./legacy-source.mjs";
import { IMPORTER_VERSION } from "./taxonomy-import.mjs";

const cmp = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
const n = (x) => String(x).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
const row = (...cells) => `| ${cells.join(" | ")} |`;
const table = (head, rows) => [row(...head), row(...head.map(() => "---")), ...rows.map((r) => row(...r))].join("\n");

function shortList(items, max = 12) {
  if (!items.length) return "none";
  const shown = items.slice(0, max).map((i) => `\`${i}\``).join(", ");
  return items.length > max ? `${shown}, and ${items.length - max} more` : shown;
}

export function renderTaxonomyReport({ report, files }) {
  const R = report.counts;
  const c = (k) => R.get(k);
  const withPrefix = (prefix) =>
    [...R.counts.keys()]
      .filter((k) => k.startsWith(prefix))
      .sort(cmp)
      .map((k) => [k.slice(prefix.length), R.get(k)]);
  const bytes = [...files.values()].reduce((s, t) => s + Buffer.byteLength(t), 0);
  const kinds = withPrefix("records:");
  const totalRecords = kinds.reduce((s, [, v]) => s + v, 0);
  const rev = report.revision;
  const out = [];
  const push = (...lines) => out.push(...lines.flatMap((l) => [l, ""]));

  push(
    "# Taxonomy import report",
    `<!-- Generated by scripts/migrate/import-taxonomy.mjs ${IMPORTER_VERSION}. Do not edit; run \`npm run migrate:taxonomy\`. -->`,
    `Source: \`${LEGACY_REPOSITORY}\` at \`${rev}\` (read-only, extracted with \`git archive\`).`,
    "This report is generated with the records. It lists what was imported, how, and what was not: dropped, ambiguous or lossy legacy fields, with counts. It is part of the traceability for issue #3 (part of #1).",
  );

  push(
    "## Summary",
    table(
      ["Canonical record kind", "Records"],
      [...kinds.map(([k, v]) => [`\`${k}\``, n(v)]), ["**total**", `**${n(totalRecords)}**`]],
    ),
    `Records are written under \`records/\` (${n(files.size)} files, ${n(Math.round(bytes / 1024))} KiB): \`providers/<provider>.json\`, \`families/<provider>/<family>.json\`, \`contracts/<provider>/<family>@<revision>.json\`, \`reviews/<provider>/<family>.json\`, and \`sources/<host>/<id>.json\`. \`variants/\` and \`siblings/\` are reserved and empty: the legacy repository holds no structured variant or benign-sibling data outside its fixtures (issue #4).`,
    table(
      ["Legacy entity", "Count", "Result"],
      [
        ["taxonomy providers", n(report.taxonomy.providers), "one `provider` each, plus `generic` (derived; see below)"],
        ["taxonomy families", n(report.taxonomy.families), "one `family`, one `format-contract@1` and one `evidence-review-history` each"],
        ["dossier family entries", n(report.dossiers.entries), `all ${n(report.dossiers.entries)} match a taxonomy family; ${n(report.dossiers.providers)} dossier files`],
        ["registry format contracts read", n(report.registry.contracts), `attached to families through taxonomy \`detectors[]\` and arrival-family taxonomy ids (${n(c("legacy:families") - R.list("family-without-registry-contract").length)} families)`],
        ["distinct legacy source URLs (fragment removed)", n(report.sources.distinct), "one `evidence-source` each"],
        ["GitHub issue references in dossiers", "see below", "`family.research.issues` and review-event `externalRefs`"],
      ],
    ),
    "Every record carries an `externalRefs` entry with `system` `legacy-taxonomy-import` whose `id` is `<legacy sha>:<legacy path>` and whose `note` names the entry inside that file. That marker also identifies the files this tool owns; `--check` never touches other records.",
  );

  push(
    "## Every imported record is a draft",
    "All imported records have `lifecycle: draft`. Import is not review: no record has passed the review-independence rule in `docs/governance/attribution.md`. The dossier verdict is preserved as a review-history event by the `legacy-import` automation actor, disclosed as `project-maintainer`. Promotion to `reviewed` is a separate, human step.",
  );

  push(
    "## Mapping decisions applied",
    "### Dossier verdict",
    table(
      ["Legacy verdict / tier", "Families", "Family research state", "Review event verdict", "Contract period"],
      withPrefix("verdict:").map(([k, v]) => {
        const [verdict, tier] = k.split("/");
        const state = { ready: "researched", "issuance-gated": "researched", "date-gated": "researched", "not-found": "not-found", rejected: "rejected", unresearched: "unresearched" }[verdict];
        const ev = { ready: "supports", "issuance-gated": "inconclusive", "date-gated": "inconclusive", "not-found": "not-assertable", rejected: "does-not-support", unresearched: "(observed, no verdict)" }[verdict];
        const period = verdict === "ready" && ["T1", "T2", "T3"].includes(tier) ? "current" : "proposed";
        return [`${verdict} / ${tier}`, n(v), state, ev, period];
      }),
    ),
    "`currentContract` is set only for a `current` period. Gated, not-found, rejected and T0 families keep a `proposed` contract so their cited sources and open state stay resolvable without asserting a format.",
    "### Evidence tier to evidence class",
    "Tiers are read only as a description of evidence quality (ADR 0001). T1 is `provider-documented`, T2 `tool-corroborated`, T3 `project-policy`, T0 and no tier `unresolved`. No tier or class is a support status, and none is carried as one.",
    "A stricter rule from `docs/governance/evidence-classes.md` is applied mechanically where it can be checked: a `tool-corroborated` claim needs artifacts from at least two distinct owners (Redact Secret's own repositories never count), otherwise the claim is imported as `unresolved`; a `provider-documented` claim needs at least one source.",
    table(
      ["Downgrade", "Claims"],
      [
        ["tool-corroborated with fewer than two distinct non-project owners, imported as unresolved", n(c("downgrade:tool-corroborated-fewer-than-two-owners"))],
        ["provider-documented without a source, imported as unresolved", n(c("downgrade:provider-documented-without-source"))],
      ],
    ),
    "### Contract field basis to evidence class",
    table(
      ["Legacy field basis / status -> class", "Field claims"],
      withPrefix("field-basis:").map(([k, v]) => [k, n(v)]),
    ),
    "Lossy on purpose: `provider-example` and `provider-code` both become `provider-documented` because `evidence-classes.md` counts provider-published examples and official provider SDK code, but the legacy basis is kept in a `legacy-field-claim` external reference on the contract (`legacy evidence basis=...`). `community`, `maintainer-observation` and `research-hypothesis` are `unresolved`: none meets an evidence class without review. The legacy field status is a benchmark reliance flag (whether fixtures depend on the field) and is dropped, except that a legacy `unresolved` status forces class `unresolved`. Dropped statuses: "+ withPrefix("dropped:field-status=").map(([k, v]) => `${k} x${v}`).join(", ") + ".",
    "### Claims produced",
    table(
      ["Evidence class", "Claims"],
      withPrefix("claims:").map(([k, v]) => [`\`${k}\``, n(v)]),
    ),
  );

  push(
    "## Legacy fields: dropped, mapped and ambiguous",
    "### `taxonomy.json`",
    table(
      ["Field", "Present on", "Disposition"],
      [
        ["providers[].id, name", n(report.taxonomy.providers), "mapped to `provider`"],
        ["families[].id, provider, name, description", n(report.taxonomy.families), "mapped to `family`; ids carried over unchanged (ADR 0002)"],
        ["families[].detectors", `${n(report.taxonomyFieldUsage.detectors ?? 0)} families with entries (${n(c("detector-refs"))} refs)`, "kept only as optional `externalRefs` (`redact-secret-detector`) on the family, per ADR 0001"],
        ["families[].sources", n(report.taxonomyFieldUsage.sources ?? 0), "`evidence-source` records and a `taxonomy-sources` claim on the family contract; the taxonomy records no date, so the dossier `researchedAt` is the observed-at date"],
        ["families[].note", n(c("mapped:taxonomy-note")), `kept verbatim as a review-history event, never as a descriptive field (${n(c("truncated:legacy-note"))} over 2000 characters, truncated with an ellipsis)`],
        ["families[].supportStatus", n(withPrefix("dropped:taxonomy.supportStatus=").reduce((s, [, v]) => s + v, 0)), "dropped: product-owned status (" + withPrefix("dropped:taxonomy.supportStatus=").map(([k, v]) => `${k} x${v}`).join(", ") + ")"],
        ["sourceNote", "1", "dropped: benchmark workflow prose"],
      ],
    ),
    "### Dossiers (`benchmarks/support/dossiers/*.md`)",
    table(
      ["Field", "Disposition"],
      [
        ["research.verdict", "`family.research.state` and a review-history event verdict (table above)"],
        ["research.tier", "evidence class of the `dossier-research` claim (table above)"],
        ["research.sources", "`evidence-source` records; cited by the `dossier-research` claim"],
        ["research.evidence", "pinned link on the review event and a cited source; every value was a 40-hex commit link"],
        ["research.issues", "`family.research.issues` and review-event `externalRefs` (`github-issue`)"],
        ["research.researchedAt", "`family.research.researchedAt` and the observed-at date of the dossier claim and its sources"],
        [`blockedBy (${n(c("mapped:blockedBy"))} families)`, `\`family.research.blockers[]\` (summary clipped to 240 characters: ${n(c("truncated:blocker-summary"))} clipped) and the full text in the review event`],
        [`markdown body (${n(report.dossiers.prose.files)} files, ${n(report.dossiers.prose.bytes)} bytes)`, "not migrated: unstructured prose (shape, issuance, collisions, open questions). Reachable through the pinned legacy path on each record. Extracting it would be hand-authored evidence without traceability"],
        [`README, template and candidates file (${report.dossiers.prose.excluded.length} files)`, "not migrated: process documents and a list of not-yet-family candidates (`_candidates-not-yet-families.md`)"],
      ],
    ),
    "### Format-contract registry (`assessment.ts` and `benchmarks/lib/beta8/*.ts`)",
    table(
      ["Field", "Contracts", "Disposition"],
      [
        ["tier", n(report.registry.fieldUsage.tier ?? 0), "evidence class only (see above); T3 and T0 also get a `legacy-contract-tier` claim"],
        ["pattern", n(report.registry.fieldUsage.pattern ?? 0), `\`structure.descriptivePattern\` for ${n(c("mapped:pattern"))}; omitted for ${n(c("omitted:pattern-of-shared-contract"))} on shared contracts (would over-claim), ${n(c("omitted:pattern-over-500"))} over 500 characters`],
        ["providerSource", n(report.registry.fieldUsage.providerSource ?? 0), "`provider-documented` claim citing the source"],
        ["candidateSource", n(report.registry.fieldUsage.candidateSource ?? 0), "`unresolved` claim: the legacy contract itself did not accept it as the provider source"],
        ["twinSource", n(report.registry.fieldUsage.twinSource ?? 0), "`provider-documented` claim for the one mutable property"],
        ["corroboration", n(report.registry.fieldUsage.corroboration ?? 0), "one `tool-corroboration` claim per contract, subject to the two-owner rule"],
        ["fields (per-field provenance)", n(report.registry.fieldUsage.fields ?? 0), "one claim per field; basis and status kept in `legacy-field-claim` references"],
        ["references", n(report.registry.fieldUsage.references ?? 0), "`unresolved` claim: the legacy contract does not say what each reference supports"],
        ["review", n(c("mapped:contract-review")), `review-history event, verbatim (${n(c("truncated:legacy-review"))} truncated at 2000 characters); the text is legacy prose and contains benchmark vocabulary`],
        ["companion", n(report.registry.fieldUsage.companion ?? 0), `\`structure.components\` entry for ${n(c("mapped:companion"))}; omitted on shared contracts (${n(c("omitted:companion-of-shared-contract"))})`],
        ["unprobeable", n(report.registry.fieldUsage.unprobeable ?? 0), "dropped: twin-authoring bookkeeping"],
        ["contextGated", n(report.registry.fieldUsage.contextGated ?? 0), "dropped: scoring mode. It hints that the family has no bare-value grammar, which is a format fact worth modelling; needs a schema decision"],
        ["structural, validate", `${n(report.registry.fieldUsage.structural ?? 0)}, ${n(report.registry.fieldUsage.validate ?? 0)}`, "dropped: executable or scoring constraints, not evidence"],
        ["arrival family `reason`, `issue`", n(report.registry.arrivalFamilies), "dropped: benchmark workflow prose and issue numbers; only the arrival-to-taxonomy id link is used"],
      ],
    ),
  );

  push(
    "## Ambiguous or lossy",
    table(
      ["Item", "Count", "What happened"],
      [
        ["Contracts shared by several families", n(R.list("shared-contract").length), "Legacy contracts are keyed by detector, and one detector covers several families. Claims and sources are attached to every family that shares the contract, each statement marked as shared; the shared regular expression is not attached to any of them"],
        ["Families with no registry contract", n(R.list("family-without-registry-contract").length), "Their contract holds only the dossier and taxonomy claims"],
        ["Families whose contract tier differs from the dossier tier", n(c("tier-mismatch:dossier-vs-contract")), "The dossier decides the contract period; the registry tier decides only the claims it produced"],
        ["Legacy links naming a tag or branch, not a commit", n(c("source-pin:moving-ref")), "The schema forbids a live GitHub file locator, so the locator is the repository and the exact legacy URL is kept in a `legacy-url` reference. Resolving them to commit permalinks needs network access and is left to a follow-up"],
        ["Source URLs with no known role", n(report.sources.ambiguousType), "`sourceType` `other`: the legacy field that cited them does not say whether they are provider documentation, a scanner rule, or a write-up"],
        ["Source URLs typed by review", n(c("source-type-reviewed")), "Left as `other` by the mechanical import, then read and typed by a person while rewriting dossier prose into family narratives (issue #16, `scripts/migrate/authored/source-types.mjs`); only `other` is ever replaced"],
        ["Claims with an inferred observed-at date", n(c("inferred-date:contract-own-earliest") + c("inferred-date:dossier-researchedAt") + c("inferred-date:taxonomy-sources-use-dossier-date")), `earliest date on the same contract (${n(c("inferred-date:contract-own-earliest"))}), or the dossier researchedAt (${n(c("inferred-date:dossier-researchedAt"))} contract claims, ${n(c("inferred-date:taxonomy-sources-use-dossier-date"))} taxonomy-source claims); legacy corroboration and reference entries carry no date`],
        ["Field claims that look like historical variants", n(R.list("candidate-variant-field").length), "Not modelled as `variant` records: naming heuristics are not evidence. Listed for a reviewer: " + shortList(R.list("candidate-variant-field"), 8)],
        ["Statements or notes over 2000 characters", n(c("truncated:claim-statement") + c("truncated:supports") + c("truncated:review-note") + c("truncated:legacy-note") + c("truncated:legacy-review") + c("truncated:family-description") + c("truncated:companion")), "Truncated with an ellipsis; the full text is at the pinned legacy path"],
        ["Provider not in the taxonomy provider list", n(R.list("derived-provider").length), "`generic` is reserved by ADR 0002 for provider-less families; its dossier and six families exist in the legacy repository but no `providers[]` entry, so the record is derived"],
        ["Detector mapped but no contract", n(R.list("detector-without-contract").length), shortList(R.list("detector-without-contract"))],
        ["Registry contracts with no family", n(R.list("contract-without-family").length), shortList(R.list("contract-without-family"))],
        ["Dossier evidence link not commit-pinned", n(R.list("dossier-evidence-not-commit-pinned").length), shortList(R.list("dossier-evidence-not-commit-pinned"))],
      ],
    ),
    "Shared contracts (contract -> families):",
    R.list("shared-contract").map((s) => `- \`${s}\``).join("\n"),
    "",
  );

  const s = report.stats;
  push(
    "## Legacy artifacts not imported here",
    table(
      ["Legacy artifact", "Size", "Disposition"],
      [
        ["`benchmarks/fixture-index.json`, `fixture-semantics.json`, `fixture-detectors.json`, corpora", `${n(s.fixtureIndex.fixtures)} fixtures in the index`, "issue #4 (cases and fixture lineage). No case or fixture record is created by this import"],
        ["`benchmarks/known-gaps.json`", `${n(s.knownGaps.issues)} issues (${Object.entries(s.knownGaps.byStatus).map(([k, v]) => `${k} ${v}`).join(", ")})`, "issue #4: observed/reviewed events attach to cases and fixtures. `promoted`, `fixed`, candidate and lifecycle fields are product workflow and are not represented"],
        ["`benchmarks/review-ledger.json`", `${n(s.reviewLedger.entries)} entries`, "not represented: per-run measurement disagreements keyed by content hash"],
        ["`benchmarks/support/empirical-observations.json`", `${n(s.empiricalObservations.families)} families`, "not imported: records observations of issued credentials. It needs a separate safety review against `docs/governance/safety.md` before any structural facts are extracted"],
        ["`benchmarks/support/status-criteria.json`, `fixture-profiles.json`, `policy-qualified-credentials.json`", `${n(s.fixtureProfiles.profiles)} profiles, ${n(s.policyQualified.entries)} policy entries`, "not represented: qualification and support-status criteria are product-owned"],
        ["`benchmarks/detectors.json`", `${n(s.detectors.entries)} entries`, "not imported except the detector ids already named by `taxonomy.json`, kept as optional external references"],
        ["`evidence/<issue>/` and `results-output`", "n/a", "not read: per-issue measurement artifacts"],
      ],
    ),
  );

  push(
    "## Round trip",
    `\`tests/migrate-taxonomy.test.mjs\` rebuilds the source set from the canonical records and checks it against the legacy URLs: all ${n(report.legacyUrls.length)} distinct legacy URLs (with fragments) are recovered exactly from \`locator\`, the \`legacy-url\` reference and the citing \`sourceRef.locator\`.`,
  );

  return `${out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}
