#!/usr/bin/env node
// npm run source:observe -- --due [flags]        which sources to re-read, most urgent first (JSON)
// npm run source:observe -- <source-id> --outcome <o> --observer <slug> [flags]
//                                                  append one observation to a source record
//
//   --due                 list sources due for a re-read; writes nothing
//     --family <id>  --provider <id>  --limit <N>  --as-of <YYYY-MM-DD|today>
//   --outcome read|unchanged|changed|unreachable|superseded
//   --observer <slug>     who read the page (never an import)
//   --observed-at <date>  default today (UTC); not in the future, not before the latest entry
//   --digest <sha256>     of the bytes you read (optional)
//   --note <text>         required for changed, unreachable, superseded: what you saw
//   --dry-run             print the record, write nothing
//   --allow-generated     write even though a migrate:* script owns the file (see below)
//   --root <dir>          another repository root (tests)
//
// This tool never fetches: you read the page, then report. It appends to `observations`; it never
// edits an earlier entry, a claim, a contract or a review history. A source written by a migrate:*
// pipeline is refused unless --allow-generated, because migrate:*:check fails on the edit and the
// next regeneration overwrites it (scripts/lib/ownership.mjs). Exit 0 ok, 1 refused, 2 usage.

import { readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve, sep } from "node:path";
import { parseArgs } from "node:util";
import { ownerOf, GENERATOR_INPUT } from "./lib/ownership.mjs";
import { dueSources, ObserveError, OUTCOMES, planObservation } from "./lib/source-observe.mjs";
import { createValidator, listJson, repoRoot } from "./lib/validator.mjs";

const fail = (code, msg) => {
  console.error(msg);
  process.exit(code);
};

let args;
try {
  args = parseArgs({
    options: {
      due: { type: "boolean" },
      family: { type: "string" },
      provider: { type: "string" },
      limit: { type: "string" },
      "as-of": { type: "string" },
      outcome: { type: "string" },
      observer: { type: "string" },
      "observed-at": { type: "string" },
      digest: { type: "string" },
      note: { type: "string" },
      "dry-run": { type: "boolean" },
      "allow-generated": { type: "boolean" },
      root: { type: "string" },
    },
    allowPositionals: true,
  });
} catch (e) {
  fail(2, e.message);
}
const o = args.values;
const root = o.root ? resolve(o.root) : repoRoot;
const todayUtc = new Date().toISOString().slice(0, 10);
const posix = (p) => p.split(sep).join("/");
const files = listJson(join(root, "records"));

if (o.due) {
  const asOf = !o["as-of"] || o["as-of"] === "today" ? todayUtc : o["as-of"];
  if (!/^\d{4}-\d{2}-\d{2}$/.test(asOf)) fail(2, "--as-of must be YYYY-MM-DD or today");
  const limit = o.limit === undefined ? Infinity : Number(o.limit);
  if (!(limit >= 1)) fail(2, "--limit takes a positive integer");
  const records = files.map((f) => JSON.parse(readFileSync(f, "utf8")));
  const due = dueSources(records, { asOf, family: o.family ?? null, provider: o.provider ?? null });
  process.stdout.write(`${JSON.stringify({ asOf, count: due.length, sources: due.slice(0, limit) }, null, 2)}\n`);
} else {
  appendObservation();
}

function appendObservation() {
  const [id] = args.positionals;
  if (!id || args.positionals.length !== 1) fail(2, "usage: npm run source:observe -- --due | <source-id> --outcome <o> --observer <slug> [--note ..]");
  const file = files.find((f) => f.endsWith(`${sep}${id}.json`) && JSON.parse(readFileSync(f, "utf8")).kind === "evidence-source");
  if (!file) fail(1, `no evidence-source with id '${id}'`);
  const bytes = readFileSync(file, "utf8");
  const source = JSON.parse(bytes);
  const rel = posix(relative(root, file));
  const owner = ownerOf(rel, source);
  if (owner !== "authored" && !o["allow-generated"]) {
    fail(1, `${rel} is generated by ${owner}: an edit fails \`npm run ${owner}:check\` and the next regeneration overwrites it.\nChange ${GENERATOR_INPUT[owner]} instead, or report the observation in the pull request. (--allow-generated overrides; do not use it in an unattended run.)`);
}
  if (o.outcome !== undefined && !OUTCOMES.includes(o.outcome)) fail(2, `--outcome must be one of ${OUTCOMES.join(", ")}`);

  let plan;
  try {
    plan = planObservation(source, bytes, { outcome: o.outcome, observer: o.observer, observedAt: o["observed-at"], digest: o.digest, note: o.note, today: todayUtc });
  } catch (e) {
    if (e instanceof ObserveError) fail(1, e.message);
    throw e;
}
  const problems = createValidator().validateRecord(plan.record);
  if (problems.length) fail(1, `the result is not a valid evidence-source:\n${problems.join("\n")}`);

  if (o["dry-run"]) process.stdout.write(plan.text);
  else {
    writeFileSync(file, plan.text);
    console.log(`appended ${plan.entry.outcome} (${plan.entry.observedAt}) to ${rel}`);
}
}
